config/routes.rb
Rails.application.routes.draw do

  root to: 'public/homes#top'

  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }


  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    get 'homes/top'
    resources :omikujis, except: [:new, :index]
  end

  scope module: :public do
    get 'homes/top'
    get 'homes/about' => 'homes#about', as: 'about'
    resources :users do
      get 'password_edit' => 'users#password_edit'
      patch 'password_update' => 'users#password_update'
    end
    resource :user_omikujis, only: [:create]
    resources :omikujis, only: [:new, :show]
    get 'choices/easy' => 'choices#easy', as: 'easy'
    get 'choices/nomal' => 'choices#nomal', as: 'nomal'
    get 'choices/hard' => 'choices#hard', as: 'hard'
    get 'choices/inferno' => 'choices#inferno', as: 'inferno'
    post 'choices/choice' => 'choices#choice', as: 'choice'
    get 'choices/result' => 'choices#result', as: 'result'
    resources :choices, only: [:new, :create, :show]
    resources :bingos, only: [:index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :user
end

app/models/omikuji.rb
class Omikuji < ApplicationRecord
  has_many :user_omikujis, dependent: :destroy

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_omikujis, dependent: :destroy
  has_many :omikujis, through: :user_omikujis
  has_many :choices, dependent: :destroy
end

app/models/user_omikuji.rb
class UserOmikuji < ApplicationRecord
  belongs_to :user
  belongs_to :omikuji

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) } # 今日
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @omikujis = Omikuji.all
    @omikuji = Omikuji.new
  end
end

app/controllers/admin/omikujis_controller.rb
class Admin::OmikujisController < ApplicationController
  def create
    @omikuji = Omikuji.new(omikuji_params)
    if @omikuji.save
      redirect_to request.referer
    else
      @omikujis = Omikuji.all
      render 'admin/homes/top'
    end
  end

  def destroy
    Omikuji.find(params[:id]).destroy
    redirect_to request.referer
  end

  private

  def omikuji_params
    params.require(:omikuji).permit(:name)
  end
end

app/controllers/admin/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admin::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/registrations_controller.rb
# frozen_string_literal: true

class Admin::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController

  def after_sign_in_path_for(resource)
    admin_homes_top_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/omikujis_helper.rb
module Admin::OmikujisHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <h4 class="m-3">おみくじ一覧</h4>
      <table class="table">
        <% @omikujis.each do |omikuji| %>
          <tr>
            <td>
              <%= omikuji.name %>
            </td>
            <td>
              <%= link_to '削除', admin_omikuji_path(omikuji), method: :delete, class: "btn btn-sm btn-danger" %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="col-6">
      <h5>
        おみくじ結果</br>
        作成フォーム
      </h5>
      <% if @omikuji.errors.any? %>
        <%= @omikuji.errors.count %>件のエラーが発生しました
        <ul>
        <% @omikuji.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      <% end %>
      <%= form_with model: @omikuji, url: admin_omikujis_path do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<header class="p-2 mb-4" style="background-color: #ff8c00;">
  <div class="text-center">
    <div>
      <%= link_to root_path do %>
        <%= image_tag '運ノ宮top.png', style: "height: 150px;" %>
      <% end %>
    </div>
    <div class="row mb-2">
      <% if user_signed_in? %>
        <div class="col-3">
          <%= link_to bingos_path, class: "btn btn-light btn-sm" do %>
            Bingo
          <% end %>
        </div>
        <div class="col-3">
          <%= link_to new_omikuji_path, class: "btn btn-light btn-sm" do %>
            おみくじ
          <% end %>
        </div>
        <div class="col-3">
          <%= link_to new_choice_path, class: "btn btn-light btn-sm" do %>
            運試し
          <% end %>
        </div>
        <div class="col-3">
          <%= link_to destroy_user_session_path, class: "btn btn-light btn-sm", method: :delete do %>
            Logout
          <% end %>
        </div>
      <% elsif admin_signed_in? %>
        <div class="col-10 text-right">
          <%= link_to destroy_admin_session_path, class: "btn btn-light btn-sm", method: :delete do %>
            Logout
          <% end %>
        </div>
      <% else %>
        <div class="col-3">
          <%= link_to about_path, class: "btn btn-light btn-sm" do %>
            Abount
          <% end %>
        </div>
        <div class="col-3">
          <%= link_to new_omikuji_path, class: "btn btn-light btn-sm" do %>
            おみくじ
          <% end %>
        </div>
        <div class="col-3">
          <%= link_to new_user_registration_path, class: "btn btn-light btn-sm" do %>
            新規登録
          <% end %>
        </div>
        <div class="col-3">
          <%= link_to new_user_session_path, class: "btn btn-light btn-sm" do %>
            ログイン
          <% end %>
        </div>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class="text-center mb-1">
        <%= link_to user_path(current_user), class: "btn btn-secondary" do %>
          <%= current_user.name %>さん
        <% end %>
      </div>
    <% end %>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Undameshi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% unless current_page?(root_path) %>
      <%= render 'layouts/header' %>
    <% end %>
    <main>
      <%= yield %>
    </main>
  </body>
</html>